---
title: "initialEDA"
output: html_document
date: "2022-10-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
data <- data.frame(read.csv("dataset.csv"))

# Extracting the variables we need from the data set
brainData <- select(data, -c('id'))
brainData[brainData == ''] <- NA
head(brainData)
str(brainData)
```

Converting categorical variables as factor
```{r}
#gender,hypertension,heart_disease,ever_married,work_type,Residence_type,smoking_status,stroke
brainData$gender = factor(brainData$gender)
brainData$hypertension = factor(brainData$hypertension)
brainData$heart_disease = factor(brainData$heart_disease)
brainData$ever_married = factor(brainData$ever_married)
brainData$work_type = factor(brainData$work_type)
brainData$Residence_type = factor(brainData$Residence_type)
brainData$smoking_status = factor(brainData$smoking_status)
brainData$stroke = factor(brainData$stroke)
str(brainData)
```

```{r results='markup'}
stroke_subset1 <- select(brainData, c('gender', 'age', 'work_type', 'smoking_status', 'stroke'))
stroke_subset1
no_na_for_smoking_status <- subset(stroke_subset1, !is.na(smoking_status))
no_na_for_smoking_status
ggplot(no_na_for_smoking_status, aes(age, smoking_status, colour = gender)) + 
  geom_point() + 
  ggtitle("Distribution for age against smoking_status")
qqnorm(no_na_for_smoking_status$age, main = "Test", col = "red")
qqline(no_na_for_smoking_status$age)
na_for_smoking <- subset(stroke_subset1, is.na(smoking_status))
na_for_smoking
people_that_had_stroke <- subset(stroke_subset1, stroke == 1)
people_that_had_stroke
people_that_did_not_have_stroke <- subset(stroke_subset1, stroke == 0)
people_that_did_not_have_stroke
```

```{r results='markup'}
corr_brain <- select_if(brainData, is.numeric)
head(corr_brain)
library("corrplot")
cor_mat <- cor(corr_brain)
corrplot(cor_mat,method="number")
pairs(brainData)
```

```{r results='markup'}
library(ggplot2)
ggplot(brainData, aes(y=avg_glucose_level, x=stroke)) + 
  geom_boxplot() + 
  geom_boxplot( colour="orange", fill="#7777cc", outlier.colour="red", outlier.shape=4, outlier.size=2) +
  labs(title="outlier in avg glucose level  not due to stroke`", x="", y = "avg glucose level")

ggplot(brainData, aes(y=bmi, x=stroke)) + 
  geom_boxplot() + 
  geom_boxplot( colour="orange", fill="#7777cc", outlier.colour="red", outlier.shape=4, outlier.size=2) +
  labs(title="outlier in bmi  not due to stroke`", x="", y = "bmi")
```
**avg glucose level of people with stroke is higher than the max of people without stroke**

```{r results='markup'}
ggplot(data=brainData, aes(bmi)) + 
  geom_histogram(breaks=seq(66, 86, by = 1), 
                 col="red", 
                 fill="blue", 
                 alpha = .7) + # opacity
  labs(x="bmi", y="Frequency") +
  labs(title="bmi histogram using `ggplot`") 


ggplot(data=brainData, aes(age)) + 
  geom_histogram(breaks=seq(66, 86, by = 1), 
                 col="red", 
                 fill="blue", 
                 alpha = .7) + # opacity
  labs(x="age", y="Frequency") +
  labs(title="bmi age using `ggplot`") 



```


```{r results='markup'}
#bmi
ggplot(data = brainData, mapping = aes(x = work_type, y = bmi)) +
  geom_boxplot()


ggplot(data = brainData, mapping = aes(x = Residence_type, y = bmi)) +
  geom_boxplot()

ggplot(data = brainData, mapping = aes(x = ever_married, y = bmi)) +
  geom_boxplot()

ggplot(data = brainData, mapping = aes(x = smoking_status, y = bmi)) +
  geom_boxplot()

ggplot(data = brainData, mapping = aes(x = hypertension, y = bmi)) +
  geom_boxplot()


```

```{r results='markup'}
#avg_glucose_level
ggplot(data = brainData, mapping = aes(x = work_type, y = avg_glucose_level)) +
  geom_boxplot()


ggplot(data = brainData, mapping = aes(x = Residence_type, y = avg_glucose_level)) +
  geom_boxplot()

ggplot(data = brainData, mapping = aes(x = ever_married, y = avg_glucose_level)) +
  geom_boxplot()

ggplot(data = brainData, mapping = aes(x = smoking_status, y = avg_glucose_level)) +
  geom_boxplot()
#hypertension high => high avg bloood sugar
ggplot(data = brainData, mapping = aes(x = hypertension, y = avg_glucose_level)) +
  geom_boxplot()


```

```{r, results='markup'}
qqnorm(brainData$age, main="Q-Q plot of age", col="blue", ylab="age quantiles")
qqline(brainData$age)
qqnorm(brainData$bmi, main="Q-Q plot of bmi", col="blue", ylab="bmi quantiles")
qqline(brainData$bmi)
qqnorm(brainData$avg_glucose_level, main="Q-Q plot of avg_glucose_level", col="blue", ylab="avg_glucose_level quantiles")
qqline(brainData$avg_glucose_level)
```

