---
title: "knn"
output: html_document
date: "2022-12-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Importing the required libraries
```{r}
# install.packages(randomForest)
library(caret)
library(dplyr)
# library(lessR)
library(randomForest)
```


##Loading both the datasets 
```{r results='markup'}
beforeSMOTE <- data.frame(read.csv("beforeSmote.csv"))
afterSMOTE <- data.frame(read.csv("afterSmote.csv"))

```

##Factoring the Categorical variables as before 
```{r results='markup'}
#factoring the dataset
beforeSMOTE$gender = factor(beforeSMOTE$gender)
beforeSMOTE$hypertension = factor(beforeSMOTE$hypertension)
beforeSMOTE$heart_disease = factor(beforeSMOTE$heart_disease)
beforeSMOTE$ever_married = factor(beforeSMOTE$ever_married)
beforeSMOTE$work_type = factor(beforeSMOTE$work_type)
beforeSMOTE$Residence_type = factor(beforeSMOTE$Residence_type)
beforeSMOTE$smoking_status = factor(beforeSMOTE$smoking_status)
beforeSMOTE$stroke = factor(beforeSMOTE$stroke)
#beforeSMOTE$glucoseGroup = factor(beforeSMOTE$glucoseGroup)
summary(beforeSMOTE)

#factoring the dataset
afterSMOTE$gender = factor(afterSMOTE$gender)
afterSMOTE$hypertension = factor(afterSMOTE$hypertension)
afterSMOTE$heart_disease = factor(afterSMOTE$heart_disease)
afterSMOTE$ever_married = factor(afterSMOTE$ever_married)
afterSMOTE$work_type = factor(afterSMOTE$work_type)
afterSMOTE$Residence_type = factor(afterSMOTE$Residence_type)
afterSMOTE$smoking_status = factor(afterSMOTE$smoking_status)
afterSMOTE$stroke = factor(afterSMOTE$stroke)
afterSMOTE$glucoseGroup = factor(afterSMOTE$glucoseGroup)
summary(afterSMOTE)

# cols <-  hcl.colors(length(levels(beforeSMOTE$stroke)), "Fall")
# PieChart(stroke, data = beforeSMOTE, hole = 0,
#          fill = cols,
#          labels_cex = 0.6)
```

### After SMOTE
```{r}
# cols <-  hcl.colors(length(levels(afterSMOTE$stroke)), "Fall")
# PieChart(stroke, data = afterSMOTE, hole = 0,
#          fill = cols,
#          labels_cex = 0.6)
```


## Setting the variable for checking 
```{r}
#set it to beforeSMOTE/afterSMOTE

#modellingDataset <- beforeSMOTE
modellingDataset <- afterSMOTE
modellingDataset <- modellingDataset %>% relocate(stroke, .after=glucoseGroup)

# str(modellingDataset)
# modellingDataset$gender <- ifelse(modellingDataset$gender == "Female", 1, 0)
# modellingDataset$ever_married <- ifelse(modellingDataset$ever_married == "Yes", 1, 0)
# modellingDataset$Residence_type <- ifelse(modellingDataset$Residence_type == "Urban", 1, 0)

# head(modellingDataset)
# table(modellingDataset$gender)

data <- dummyVars("stroke ~ .", data = modellingDataset, fullRank = T)
custom_data <- data.frame(predict(data, newdata = modellingDataset))

length(custom_data)
head(custom_data)
# glimpse(custom_data)
# head(custom_data)
```


## Splitting the dataset into train and test 
```{r}
library(dplyr)

set.seed(123)  
split1<- sample(c(rep(0, 0.7 * nrow(custom_data)), rep(1, 0.3 * nrow(custom_data))))
table(split1) 
#train split
train <- custom_data[split1 == 0, 0:16]
#test split
test <- custom_data[split1== 1, 0:16] 

split1.trainLabels <- modellingDataset[split1==0, 12]
split1.testLabels <- modellingDataset[split1==1, 12]
```

##KNN
```{r, results='markup'}

library(FNN)
library(gmodels)
library(caret)


ResultDf = data.frame( k=numeric(0), Total.Accuracy= numeric(0), row.names = NULL )

for (kval in 3:15) {
  prediction <- knn(train = train, test = test, cl=split1.trainLabels, k=kval)

  cm = confusionMatrix(prediction, reference = split1.testLabels )

  cmaccu = cm$overall['Accuracy']

  cmt = data.frame(k=kval, Total.Accuracy = cmaccu, row.names = NULL )
  ResultDf = rbind(ResultDf, cmt)
}

xkabledply(ResultDf, "Total Accuracy Summary")
best_accuracy <- ResultDf[which.max(ResultDf$Total.Accuracy),]
k_value <- best_accuracy$k

pred_best <- knn(train =train, test = test, cl=split1.trainLabels, k=k_value, prob=TRUE)
PIMAPREDCross_best <- CrossTable(split1.testLabels, pred_best, prop.chisq = FALSE)
cm_best = confusionMatrix(pred_best, reference = split1.testLabels )

xkabledply(as.matrix(cm_best), title = paste("ConfusionMatrix for k = ",k_value))
xkabledply(data.frame(cm_best$byClass), title=paste("k = ",k_value))

```










