---
title: "Modelling"
author: "Team 6"
date: "2022-11-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Importing the required libraries
```{r}
install.packages(randomForest)
library(caret)
library(dplyr)
library(lessR)
library(randomForest)
```

##Factoring the Categorical variables as before 
```{r results='markup'}
#factoring the dataset
##Loading both the datasets 
beforeSMOTE <- data.frame(read.csv("trainDataBeforeSmote.csv"))
afterSMOTE <- data.frame(read.csv("trainDataAfterSmote.csv"))
test <- data.frame(read.csv("test.csv"))

##Factoring the Categorical variables as before 
beforeSMOTE$gender = factor(beforeSMOTE$gender)
beforeSMOTE$hypertension = factor(beforeSMOTE$hypertension)
beforeSMOTE$heart_disease = factor(beforeSMOTE$heart_disease)
beforeSMOTE$ever_married = factor(beforeSMOTE$ever_married)
beforeSMOTE$work_type = factor(beforeSMOTE$work_type)
beforeSMOTE$Residence_type = factor(beforeSMOTE$Residence_type)
beforeSMOTE$glucoseGroup = factor(beforeSMOTE$glucoseGroup)
beforeSMOTE$smoking_status = factor(beforeSMOTE$smoking_status)
beforeSMOTE$stroke = factor(beforeSMOTE$stroke)
summary(beforeSMOTE)

#factoring the dataset
afterSMOTE$gender = factor(afterSMOTE$gender)
afterSMOTE$hypertension = factor(afterSMOTE$hypertension)
afterSMOTE$heart_disease = factor(afterSMOTE$heart_disease)
afterSMOTE$ever_married = factor(afterSMOTE$ever_married)
afterSMOTE$work_type = factor(afterSMOTE$work_type)
afterSMOTE$Residence_type = factor(afterSMOTE$Residence_type)
afterSMOTE$smoking_status = factor(afterSMOTE$smoking_status)
afterSMOTE$stroke = factor(afterSMOTE$stroke)
afterSMOTE$glucoseGroup = factor(afterSMOTE$glucoseGroup)
summary(afterSMOTE)

#testing 
#factoring the dataset
test$gender = factor(test$gender)
test$hypertension = factor(test$hypertension)
test$heart_disease = factor(test$heart_disease)
test$ever_married = factor(test$ever_married)
test$work_type = factor(test$work_type)
test$Residence_type = factor(test$Residence_type)
test$smoking_status = factor(test$smoking_status)
test$stroke = factor(test$stroke)
test$glucoseGroup = factor(test$glucoseGroup)
summary(test)

cols <-  hcl.colors(length(levels(beforeSMOTE$stroke)), "Fall")
PieChart(stroke, data = beforeSMOTE, hole = 0,
         fill = cols,
         labels_cex = 0.6)
```

### After SMOTE
```{r}
cols <-  hcl.colors(length(levels(afterSMOTE$stroke)), "Fall")
PieChart(stroke, data = afterSMOTE, hole = 0,
         fill = cols,
         labels_cex = 0.6)
```



```{r, results='markup'}
rfBS <- randomForest(stroke~., data=beforeSMOTE, proximity=TRUE)
```

```{r, results='markup'}
summary(rfBS)
```

```{r, results='markup'}
predict_testBS = predict(rfBS, test)
confusionMatrix(predict_testBS, test$stroke)
```
```{r}
head(beforeSMOTE)
```

```{r, results='markup'}
rfBS2 <- randomForest(stroke~age+hypertension+heart_disease+avg_glucose_level, data=beforeSMOTE, proximity=TRUE)
```

```{r, results='markup'}
predict_testBS2 = predict(rfBS2, test)
confusionMatrix(predict_testBS2, test$stroke)
```

```{r, results='markup'}
rfBS3 <- randomForest(stroke~age:hypertension+age:heart_disease+bmi, data=beforeSMOTE, proximity=TRUE)
```

```{r, results='markup'}
predict_testBS3 = predict(rfBS3, test)
confusionMatrix(predict_testBS3, test$stroke)
```

```{r}
print(rfBS3)
```
```{r}
trControl <- trainControl(method = "cv",
    number = 10,
    search = "grid")
```

```{r}
# rf_cvBS <- train(stroke~.,
#     data = train,
#     method = "rf",
#     metric = "Accuracy",
#     trControl = trControl)
# # Print the results
# print(rf_cvBS)

```


```{r}
# rf_cvBS1 <- train(stroke~age+hypertension+heart_disease+avg_glucose_level,
#     data = beforeSMOTE,
#     method = "rf",
#     metric = "Accuracy",
#     trControl = trControl)
# # Print the results
# print(rf_cvBS1)

```



```{r}
# rf_cvBS2 <- train(stroke~age:hypertension+age:heart_disease+bmi,
#     data = beforeSMOTE,
#     method = "rf",
#     metric = "Accuracy",
#     trControl = trControl)
# # Print the results
# print(rf_cvBS2)

```



```{r}
plot(rfBS)
plot(rfBS2)
plot(rfBS3)
```

```{r}
varImpPlot(rfBS)
```
```{r}
varImpPlot(rfBS2)
```

```{r}
varImpPlot(rfBS3)
```
```{r}
colnames(beforeSMOTE)
```



```{r, results='markup'}
rfBS4 <- randomForest(stroke~bmi+avg_glucose_level, data=beforeSMOTE, proximity=TRUE)
print(rfBS4)
```

```{r, results='markup'}
rfBS5 <- randomForest(stroke~age, data=beforeSMOTE, proximity=TRUE)
print(rfBS5)
```



```{r, results='markup'}
predict_testBS4 = predict(rfBS4, test)
confusionMatrix(predict_testBS4, test$stroke)
```

```{r, results='markup'}
predict_testBS5 = predict(rfBS5, test)
confusionMatrix(predict_testBS5, test$stroke)
```


```{r}
# rf_cvBS5 <- train(stroke~age,
#     data = beforeSMOTE,
#     method = "rf",
#     metric = "Accuracy",
#     trControl = trControl)
# # Print the results
# print(rf_cvBS5)

```

```{r}
summary(test)
```



```{r}
partialPlot(rfBS3, beforeSMOTE, age, "1")
```



```{r}
library(pROC)
rf_predictionBS <- predict(rfBS3, test, type = "prob")
ROC_rfBS <- roc(test$stroke, rf_predictionBS[,2])
ROC_rf_aucBS <- auc(ROC_rfBS)
plot(ROC_rfBS, col = "green", main = "ROC For Random Forest")

paste("Area under curve of random forest: ", ROC_rf_aucBS)

```








